name: esaturasi
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies: 
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  http: 1.3.0
  shared_preferences: ^2.5.2
  intl: ^0.19.0  
  timeago: ^3.6.0
  table_calendar: ^3.0.0
  flutter_native_splash: ^2.3.6
  image_picker: ^0.8.6
  cached_network_image: ^3.2.3
  percent_indicator: ^4.2.3
  flutter_html: ^3.0.0-beta.2
  share_plus: ^7.0.2
  path_provider: ^2.1.1
  url_launcher: ^6.1.11
  dio: ^5.3.2
  file_picker: 10.1.2


  flutter_localizations:
    sdk: flutter  
  permission_handler: ^12.0.0+1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/logo.png
    - assets/images/artikel/wisuda.png
    - assets/images/artikel/kunjungan.png
    - assets/images/artikel/sepakbola.png
    - assets/images/ic_lonceng.png
    - assets/images/ic_jamnew.png
    - assets/images/ic_tugasnew.png
    - assets/images/ic_mapelnew.png
    - assets/images/ic_kalendernew.png
    - assets/images/splashscreen.png
    - assets/images/logosmk.png
